package com.example.demo.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-03T15:55:53.818+08:00
 * Generated source version: 3.4.2
 *
 */
@WebServiceClient(name = "HelloWebService",
                  wsdlLocation = "http://10.18.23.135:8082/ws/helloWebService?wsdl",
                  targetNamespace = "xb.ceair.com")
public class HelloWebService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("xb.ceair.com", "HelloWebService");
    public final static QName HelloWebServiceImplPort = new QName("xb.ceair.com", "HelloWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.18.23.135:8082/ws/helloWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWebService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.18.23.135:8082/ws/helloWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWebService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HelloWebService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWebService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HelloWebService
     */
    @WebEndpoint(name = "HelloWebServiceImplPort")
    public HelloWebService getHelloWebServiceImplPort() {
        return super.getPort(HelloWebServiceImplPort, HelloWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWebService
     */
    @WebEndpoint(name = "HelloWebServiceImplPort")
    public HelloWebService getHelloWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(HelloWebServiceImplPort, HelloWebService.class, features);
    }

}
