
package com.example.demo.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-03T15:55:53.815+08:00
 * Generated source version: 3.4.2
 *
 */

public class HelloWebService_HelloWebServiceImplPort_Server{

    protected HelloWebService_HelloWebServiceImplPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloWebServiceImplPortImpl();
        String address = "http://10.18.23.135:8082/ws/helloWebService";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new HelloWebService_HelloWebServiceImplPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
